### ISSUE TITLE
specttool.c:610:31: fatal error: numpy/arrayobject.h: No such file or directory

### ISSUE THREAD

**Issue by expectopatronum** [rgcda/Musisep#2]
Hi,
I have some difficulties installing musisep.
I am using Python 3.5 (on Ubuntu 16.04.6 LTS), and all the mentioned versions of the Python packages (except for pyFFTW, I am using 0.12.0, when I tried to install 0.10.4 it failed with some error).

I also installed `cython3` using `apt install cython3`.

When calling `make -C musisep/audio` I get the following output:
```
make: Entering directory '/home/verena/Repos/Musisep/musisep/audio'
gcc -I/usr/include/python3.5 -shared -pthread -fPIC -fwrapv -O2 -fno-strict-aliasing -fopenmp -o specttool.so specttool.c
specttool.c:610:31: fatal error: numpy/arrayobject.h: No such file or directory
compilation terminated.
Makefile:10: recipe for target 'specttool.so' failed
make: *** [specttool.so] Error 1
make: Leaving directory '/home/verena/Repos/Musisep/musisep/audio'
```
I tried the same on a new machine (Ubuntu 20.04) but with Python 3.7 and some of the Python packages in a newer version, with the same result.

I don't have much experience with make files and also couldn't find anything helpful on Google, so I am not sure if this is a problem of my setup or a problem of the make file. 
Please let me know if there is anything obvious that I am doing wrong or any other information I can provide.

Thanks in advance and best regards
Verena

**Comment by expectopatronum** [comment]
As usual, right after I posted this issue, I found the solution. For the installation to work, it requires `numpy` installed with apt, and not with pip.
```
apt install python3-numpy
```
I'll leave it here and close this issue, maybe someone else will find it useful.
Best regards
Verena

**Comment by sdschulze** [comment]
You may need to change some paths in the Makefile depending on the Python installation you are using.
